#!/bin/bash

KEY=""
for ARG in "$@"
do
	if [[ $ARG = \-* ]]; then
		if [ -n "$KEY" ]; then
			eval ${KEY}=true
		fi
		KEY=${ARG:1}
	else
		if [ -n "$KEY" ]; then
			eval ${KEY}=$ARG
		fi
		KEY=""
	fi
done

if [ -n "$KEY" ]; then
	eval ${KEY}=true
fi

if [ -z "$locale" ]; then
	locale=en_US
fi
if [ -z "$site" ]; then
	site=eynoaf
fi

uglifyjs --source-map dist/$site.min.js.map -o dist/$site.min.js js/ui.js js/locale/$locale.js js/accordion.js js/drilldown.js js/embed.js js/mime-type-icons.js js/uploader.js js/filedrop.js js/offcanvas.js js/scrollable-topbar.js js/tabs.js js/tooltip.js